### PR TITLE
Update Chinese localization

### PR DESCRIPTION
**Pull request by atticus-lv**
notes: some where has "label" , I have remove ""

### CODE REVIEW

**Comment by Woprok** [comment]
The original file had correct columns, only 3 are required: ID, SourceText, TranslatedText. These 3 are columns in automatically generated file when new translation is added.

**Comment by atticus-lv** [comment]
where shoult I modify, seems the old one is alreadly correct? Can you give me a empty list to fill in ?

**Comment by Woprok** [comment]
> where shoult I modify, seems the old one is alreadly correct? Can you give me a empty list to fill in ?



just take [current ](https://raw.githubusercontent.com/Woprok/AOE4-AdvancedGameSettings/master/assets/locdb/Advanced%20Game%20Settings_zh-hans.csv) version that is still in this repository. Csv is pure text...  so just added missing lines to it. Then just check that all translations are ok and equal to English version. 

Following lines are either missing or not translated in current version:
`
359,,Low
360,,"Conquer majority of city-states to ensure victory. Each players starts with few monks and has to find and takeover city.\nCivilization choice has no effect. Population is limited to 150. Team that controls 75% of cities will win the game.\n\nHelp, feedback, bug reports and contribution to mode can be done at:\nhttps://github.com/search?q=AOE4-AdvancedGameSettings"
361,,City-State Wars
362,,Control majority of cities
363,,City %1NAMEORNUMBER% 
364,,%1PLAYER_NAME% was assimilated
365,,You are approaching Culture Victory
366,,Your team is approaching Culture Victory
367,,Enemy is approaching Culture Victory
368,,Capturing City-State
369,,Ally capturing City-State
370,,Enemy capturing City-State
371,,City-State captured
372,,Ally captured City-State
373,,Enemy captured City-State
374,,Contesting City-State
375,,Ally contesting City-State
376,,Enemy contesting City-State
377,,Liberated City-State
378,,Ally liberated City-State
379,,City-State lost
380,,Liberating City-State
381,,Ally liberating City-State
382,,Enemy liberating City-State
383,,Team Conquest
384,,"Players are conquered only if all their teammates conquerable buildings are destroyed. Does not work with diplomacy teams, due to how relations work."
`

**Comment by atticus-lv** [comment]
add a new pull request

**Pull request closed without merging**
