### PR TITLE
added option for houses population capacity

### PR DESCRIPTION
**Pull request by dirtyharryiv**
Hi!

I found it very useful to have an option for changing the population capacity of houses.
Maybe you can merge my changes. I haven't tested if the work with other languages though...

wbr 
dirtyharryiv

### CODE REVIEW

**Comment by Woprok** [comment]
You are removing wrong modifier on destruction. You need to remove modifier that is tied to destroyed house ENTITY UNIQUE ID. (Removing last will result in scenario where P1 built house, P2 built house, P1 deleted house, P2 lost modifier)
So you also need to store it under that ID in the list. Or have separate list of modifiers for each player, otherwise it will not work correctly. Probably best way to do it is to have separate list of modifiers for each player... (less work for same effect as keeping EntityUniqueID)

**Comment by dirtyharryiv** [comment]
Thanks for the hint! I noticed it yesterday while playing...
I'll try to fix it.

**Comment by dirtyharryiv** [comment]
So this worked for me. Maybe you can check again?!

**Comment by Woprok** [comment]
Looks fine to me. I will merge it later.

**Review by Woprok — APPROVED** [review]

**Pull request merged**
